### ISSUE TITLE
Postinstall script is failed on Travis

### ISSUE THREAD

**Issue by imdrasil** [crystal-ameba/ameba#116]
Crystal: 0.31.0
Ameba: 0.10.1

Do you have any idea why Ameba is failed on the latest crystal on Travis?

```
Postinstall make bin && make run_file
Failed make bin && make run_file:
/usr/bin/shards build 
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
/usr/bin/ld: /usr/bin/../lib/crystal/lib/libgc.a(alloc.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/travis/build/imdrasil/jennifer.cr/lib/ameba/bin/ameba'  -rdynamic  -lyaml -lpcre -lm /usr/bin/../lib/crystal/lib/libgc.a -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/bin/../lib/crystal/lib -L/usr/lib -L/usr/local/l
```

Travis build: https://travis-ci.org/imdrasil/jennifer.cr/jobs/591218579

**Comment by veelenga** [comment]
Trying to reproduce. Can you try to add `--no-debug` to `CRFLAGS` env var in your Travis config and see if it helps.

**Comment by imdrasil** [comment]
the [output](https://travis-ci.org/imdrasil/jennifer.cr/jobs/591503896) is still the same

**Comment by imdrasil** [comment]
upgraded to 0.31.1

**Comment by imdrasil** [comment]
the issue was in docker image ([link](https://travis-ci.community/t/fails-to-link-against-libgc-a-in-crystal-0-31-0/5197)). sorry for the disturbing

**Comment by veelenga** [comment]
@imdrasil is this solved? Can you post some instructions ?

**Comment by imdrasil** [comment]
ATM I can't build [jennifer](https://github.com/imdrasil/jennifer.cr) on travis. Waiting for docker image being update and continue investigating this issue. Will return here if any long term workaround should be used in this case
