### ISSUE TITLE
Incorrect useless variable assignment 

### ISSUE THREAD

**Issue by wrq** [crystal-ameba/ameba#126]
`puts 45.to_s(base = 16)`

considering this very simple snippet, ameba responds:

```
badlint.cr:1:14
[W] Lint/UselessAssign: Useless assignment to variable 'base'
> puts 45.to_s(base = 16)
              ^
Finished in 20.98 milliseconds
```

Not sure where I'd even begin to try and correct this? Maybe with how Ameba parses named arguments? No idea, tbh.

**Comment by Sija** [comment]
That's a correct warning. `foo = bar` is an assignment.
What you probably wanted to do is `puts 45.to_s(base: 16)`.

**Comment by wrq** [comment]
Oh!!!

I'm sorry about that! Simple mistake
