### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by Acciaiodigitale** [crystal-ameba/ameba#133]
Hi @veelenga. I try to Sponsor you via Liberapay but says:

>  Cannot be renewed because the account of the recipient isn't ready to receive new payments.

**Comment by veelenga** [comment]
It should work now. Thanks for the interest and the notice.

**Comment by Acciaiodigitale** [comment]
Doesn't work. Sorry.
I think you can try with Patreon or Bountysource because I think the problem is about plattform

**Comment by veelenga** [comment]
Hm, strange.

Just created the Patreon acc: https://www.patreon.com/veelenga

Thanks

**Comment by Acciaiodigitale** [comment]
And this works!
