### ISSUE TITLE
Incorrectly reporting Lint/ShadowingOuterLocalVar

### ISSUE THREAD

**Issue by gdotdesign** [crystal-ameba/ameba#147]
I think I found an incorrect example for the `Lint/ShadowingOuterLocalVar` rule:

SSCCE:
```crystal
[0..10].each do |item|
  puts item
end

item = "ASD"
```

for which I get:
```
[W] Lint/ShadowingOuterLocalVar: Shadowing outer local variable `item`
> [0..10].each do |item|
                   ^
```

**Comment by veelenga** [comment]
This is fixed by 458c49273000a99798ac04acee50ef7755595935.

I will publish a new release soon.

Thanks for reporting.
