### ISSUE TITLE
ConstantNames rule conflicts with good practice defined in Crystal book about new log system

### ISSUE THREAD

**Issue by anykeyh** [crystal-ameba/ameba#148]
According to Crystal book, it's recommended top create a scoped version of a Log using `::Log.for` into a specific module or class.

```
[C] Style/ConstantNames: Constant name should be screaming-cased: LOG, not Log
> Log = ::Log.for("clear")
```

This, however, triggers error as ameba expects `LOG` instead of Log

**Comment by veelenga** [comment]
It conflicts with "Coding style" described in Crystal book too:

https://crystal-lang.org/reference/conventions/coding_style.html

```
Constants are screaming-cased. For example:

LUCKY_NUMBERS     = [3, 7, 11]
DOCUMENTATION_URL = "http://crystal-lang.org/docs"
```

**Comment by veelenga** [comment]
I see two options here:

* make `Log` constant an exception
* or allow constant to be in pascal case (i.e. `Log`, `SuperConstant`)

**Comment by Sija** [comment]
I'd raise that issue on the Crystal's bug tracker or forum.

**Comment by veelenga** [comment]
I temporarily adjusted the rule to allow both a screaming case and pascal case in constant names. Going to prepare a bugfix release together with other fixes.

Also posted a question here https://forum.crystal-lang.org/t/constant-names-coding-style-log-samples-violation/1954
