### ISSUE TITLE
New Rule: Value same as default

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-ameba/ameba#149]
Given the following scenario:

```cr
def run(debug : Bool = false)
  # Do something
end

run false
```

A new rule could warn the user that the argument to `#run` is redundant, since it's the same as the default value.

**Comment by straight-shoota** [comment]
I don't think this is a good idea. If you want to be expressive about it, what's wrong with that? Also defaults can change.

**Comment by Blacksmoke16** [comment]
It maybe doesn't need to be enabled by default.  It would be good to at least have the option of checking for this.

**Comment by Sija** [comment]
Vote to close.

**Comment by veelenga** [comment]
I agree. I don't think that this rule is going to be usable being disabled.
