### ISSUE TITLE
Crystal Log constant being flagged

### ISSUE THREAD

**Issue by drujensen** [crystal-ameba/ameba#155]
In the Crystal documentation for Log, https://crystal-lang.org/api/0.34.0/Log.html

A recommended pattern is to declare a Log constant in the namespace of your shard or module as follows:
```
module DB
  Log = ::Log.for("db") # => Log for db source

  def do_something
    Log.info { "this is logged in db source" }
  end
end
```

This is being flagged by `Style/ConstantNames` that it should be screaming case.

I'm not sure which is better, adding an exception for `Log` in Ameba or asking the Crystal team to change the recommendation.

**Comment by Blacksmoke16** [comment]
This should have been fixed in478da94c20b8ab11eafe2a079213fb9ef14e94a3, but sure you have an up to date version.

**Comment by drujensen** [comment]
my bad. thanks!
