### ISSUE TITLE
New Rule: Block not captured 

### ISSUE THREAD

**Issue by j8r** [crystal-ameba/ameba#158]
Anonymous block annotations are present since a bit of time now. Adding `&` shows that the method yields a block, but using `&block` either means that or that the block is captured.

Here is a simple example:
```cr
# Valid
def m(&block)
  block.call 1
end

# Also valid
def m(&block)
  callback = block
end

# Invalid
def m(&block)
  yield
end

# Correct syntax
def m(&)
  yield
end
```

**Comment by veelenga** [comment]
Basically, we would like to report if there is a `block` argument and it is not used. Is this correct?

**Comment by Sija** [comment]
Hmm, this should be already covered by `Lint/UnusedArgument` rule 🤔

**Comment by straight-shoota** [comment]
And eventually by `crystal tool format` (https://github.com/crystal-lang/crystal/issues/8764)

**Comment by veelenga** [comment]
That's strange. It is being covered by specs:

https://github.com/crystal-ameba/ameba/blob/be65ba2a92d1a1338cb1a13e2cb45d4161d1a400/spec/ameba/rule/lint/unused_argument_spec.cr#L118-L133

But you are right, it doesn't work on the example in the description.

**Comment by Sija** [comment]
> That's strange. It is covered by specs:

@veelenga I know, I was trying to understand wtf is goin' on there, but to no avail yet.
