### ISSUE TITLE
Incorrect line position in "Unknown yaml attribute" error

### ISSUE THREAD

**Issue by veelenga** [crystal-ameba/ameba#159]
Configuration file is strict now:

https://github.com/crystal-ameba/ameba/blob/3448de30daaf5e206a0c52132e11a47f7e8d0d6d/src/ameba/config.cr#L269

Which is nice, because incorrect attributes are now reported rather than ignored.

However, since we manually pass the rule-specific configuration, the YAML parser incorrectly reports the line of the incorrect attribute.

```sh
$ ameba
Error: Config file is invalid: Unknown yaml attribute: BadAttr at line 69, column 1
```

```sh
$ cat -n .ameba.yml | grep -C 10 BadAttr                                                               ✭
   299    - src/compiler/crystal/semantic/recursive_struct_checker.cr
   300    - src/compiler/crystal/semantic/call.cr
   301    - src/compiler/crystal/semantic/restrictions.cr
   302    - src/compiler/crystal/semantic/cleanup_transformer.cr
   303    - src/compiler/crystal/semantic/abstract_def_checker.cr
   304    - src/compiler/crystal/semantic/bindings.cr
   305    - src/compiler/crystal/semantic/new.cr
   306    - src/compiler/crystal/syntax/parser.cr
   307    - src/socket/tcp_server.cr
   308    Enabled: true
   309    BadAttr: false                # <--- LINE 309, NOT 69
   310    Severity: Warning
   311
   312  # Problems found: 1
   313  # Run `ameba --only Performance/SizeAfterFilter` for details
   314  Performance/SizeAfterFilter:
   315    FilterNames:
   316    - select
   317    - reject
   318    Description: Identifies usage of `size` calls that follow filter
   319    Excluded:

```

**Comment by Sija** [comment]
Isn't it a bug in Crystal's stdlib?

**Comment by straight-shoota** [comment]
@Sija The line numbers are messed up because ameba splits each rule into a separate piece and then parses that again using the pull parser:

https://github.com/crystal-ameba/ameba/blob/3448de30daaf5e206a0c52132e11a47f7e8d0d6d/src/ameba/config.cr#L271-L275

That's seems really messed up, though. And there's no way to restore the original line numbers with that approach. Theoretically, you could add the start position in the original file to the `YAML::ParseException#line_number`. But the `YAML::Any`-based original parse step doesn't provide these start positions.

@veelenga Why don't you parse the entire config with a pull parser directly? That `YAML::Any` step seems to be really confusing.

**Comment by veelenga** [comment]
Yes, this is a correct explanation, thanks.

> And there's no way to restore the original line numbers with that approach.

I don't plan to restore the line number. Showing the rule name + the name of the wrong attribute is completely enough. 

> Why don't you parse the entire config with a pull parser directly?

@straight-shoota the reason was to simplify the end-user config structure, avoiding the YAML nesting, unnecessary arrays, and type declarations, etc.  And I think this was the right decision since in the scope of Ameba the rules are the main entities to re-configure.

```yml

# .ameba.yml

Performance/SizeAfterFilter:
  FilterNames:
  - select
  - reject
  Description: Identifies usage of `size` calls that follow filter
  Enabled: true

Lint/UnreachableCode:
  Description: Reports unreachable code
  Enabled: true
  Severity: Warning
```

Obviously, the `YAML.mapping` neither the `YAML::Serializable` does not provide any better way to serialize this kind of config, where rule-specific settings sit at the top level and the key represents the rule name. 

However, I will give it a shot and will try using the lower level pull parser, thanks.
