### ISSUE TITLE
Questionable UselessAssign warning

### ISSUE THREAD

**Issue by stephendolan** [crystal-ameba/ameba#164]
I recently opened [a PR](https://github.com/luckyframework/lucky_cli/pull/538) to integrate Ameba into the [Lucky CLI](https://github.com/luckyframework/lucky_cli), and noticed an odd scenario that I didn't think should raise a `Lint/UselessAssign` warning.

Here's the function ([full source as well](https://github.com/luckyframework/lucky_cli/blob/master/src/api_authentication_app_skeleton/src/models/user_token.cr#L16-L22))

```crystal
  def self.decode_user_id(token : String) : Int64?
    payload, _header = JWT.decode(token, Lucky::Server.settings.secret_key_base, ALGORITHM)
    payload["user_id"].to_s.to_i64
  rescue e : JWT::Error
    Lucky::Log.dexter.error { {jwt_decode_error: e.message} }
    nil
  end
```

And the error:

```
Lint/UselessAssign: Useless assignment to variable `_header`
```

It seems as though Ameba is indicating that `_header` should simply be `_`, as the warning goes away when I make that change. However, I'd expect that it leverages the same behavior as an unused block parameter, where leaving information about which specific parameter is not being used still provides value to readers of the code.

I also could be missing a simple Crystal way to make this more clear, which I'm certainly open to!

**Comment by veelenga** [comment]
Good point. I made a fix in develop branch. If you need, i can prepare a tiny bugfix release soon.

**Comment by paulcsmith** [comment]
That's awesome! Thanks @veelenga!

**Comment by stephendolan** [comment]
Yes, thanks so much for the quick feedback @veelenga, and for your work on a truly excellent tool.
