### ISSUE TITLE
Docker Image 

### ISSUE THREAD

**Issue by marghidanu** [crystal-ameba/ameba#166]
Please publish Docker image so we can use ameba with CI pipelines.

**Comment by veelenga** [comment]
Yup, will do.

**Comment by veelenga** [comment]
https://hub.docker.com/r/veelenga/ameba

```
$ docker pull veelenga/ameba:v0.13.2
$ docker run -v $(pwd):/src veelenga/ameba:v0.13.2                                                                                                                                             ⏎
Inspecting 162 files.

..................................................................................................................................................................

Finished in 709.72 milliseconds

162 inspected, 0 failures.

```

**Comment by marghidanu** [comment]
WOW SUPER! Thanks for this, will add it to the CI pipeline now.

**Comment by bestwebua** [comment]
Hi, bro! It would be great if you will add latest lable for ameba docker image:

```bash
$ docker pull veelenga/ameba:latest
# => Error response from daemon: manifest for veelenga/ameba:latest not found: manifest unknown: manifest unknown
```

Also with this tag everybody can pull latest ameba image with shortcut:

```bash
$ docker pull veelenga/ameba
```

Just add docker tag `latest` for master branch in **Automated Builds** on docker hub.
You can configure it in **Build configurations**:

<img width="1170" alt="Screenshot 2020-11-20 at 10 15 28 PM" src="https://user-images.githubusercontent.com/14002692/99845879-0a15b300-2b7e-11eb-9043-fa75cc2e6124.png">

Cheers!

**Comment by veelenga** [comment]
@bestwebua done, thanks.

```
$ docker pull veelenga/ameba:latest
$ docker run -v $(pwd):/src veelenga/ameba:latest
```
