### ISSUE TITLE
Ameba does not install on FreeBSD

### ISSUE THREAD

**Issue by yujiri8** [crystal-ameba/ameba#167]
Ameba's postinstall script seems to not work on FreeBSD. I initialized an empty project with `crystal init app .`, added the following to `shard.yml`:
```yaml
dependencies:
  ameba:
    github: crystal-ameba/ameba
```
And ran `shards`. Error message:
```
Resolving dependencies
Fetching https://github.com/crystal-ameba/ameba.git
Installing ameba (0.13.2)
Postinstall of ameba: make bin && make run_file
Failed postinstall of ameba on make bin && make run_file:
build
make: exec(build) failed (No such file or directory)
*** Error code 1

Stop.
make: stopped in <project dir>/lib/ameba
```
This is a FreeBSD machine that has GNU make installed from packages (though I suspect the problem is that the FreeBSD package installs GNU make as `gmake` since `make` is BSD make).

**Comment by yujiri8** [comment]
The error is also produced using `version: ~> 0.12.0` as mentioned in the README.

**Comment by veelenga** [comment]
@yujiri8 `0.12.0` in readme is a mistake, I've just corrected it. Will try to reproduce the issue with make and fix. Thanks for the heads-up

**Comment by veelenga** [comment]
Hm, I thought I would be able to run FreeBSD docker container on Mac, but seems like FreeBSD containers must be run from FreeBSD hosts. 

@yujiri8 I would like to ask you for helping me with this and providing a fix before I ended up running FreeBSD, on top of Vagrant, on top of macOS. Will that be possible for you?

**Comment by yujiri8** [comment]
I was right that the problem is GNU make vs BSD make. BSD make doesn't support the `$(shell )` syntax for running shell commands. As far as I can tell, it only supports `var != command`, but that isn't the same as GNU's `?=`, it's like `:=`. I'm not sure about a compatible alternative to `?=`.

Here are some links I read:
https://www.gnu.org/software/make/manual/html_node/Setting.html
https://stackoverflow.com/questions/52912099/how-to-conditionally-assign-value-to-a-variable-in-a-makefile-bsd-gnu/52912640
https://stackoverflow.com/questions/21874468/run-a-command-in-gnu-and-bsd-makefile-and-store-the-result-into-a-variable
https://stackoverflow.com/questions/2019989/how-to-assign-the-output-of-a-command-to-a-makefile-variable

Ugghhhh this is why I hate `make`...

**Comment by straight-shoota** [comment]
The best solution, in general, is to just use GNU make on FreeBSD.
For a postinstall hook that might not be feasible, though. But it probably shouldn't need a makefile recipe. A simple, portable build script would do. In the end, it's just a `shards build` command.
