### ISSUE TITLE
[Feature Request] Always-truthy types in boolean contexts

### ISSUE THREAD

**Issue by HertzDevil** [crystal-ameba/ameba#170]
If a type isn't a `Bool`, `Nil`, `Pointer(T)`, or any union containing these types, then variables of that type are always truthy in a boolean context, regardless of their actual values; similarly, conditions of type `Nil` are always falsey. This relies on the fact that truthiness cannot be redefined by the user. Thus, it is pointless to use these types as conditions:

```crystal
def f(cond : String)
  # all the 1s are printed and all the raises are unreachable code
  cond && puts 1
  cond || raise "no"

  puts 1 if cond
  raise "no" unless cond

  while cond; puts 1 end
  until cond; raise "no" end

  case
  when cond; puts 1
  else; raise "no" # Lint/UnreachableCode
  end
end
```

It would be nice if Ameba is able to detect them (except possibly if there is a macro or type var).

Such a rule would also catch some cases of #163:

```crystal
var = 1

puts "foo" if var = 1
# var is deduced to be of type Int32
# typeof(var = 1) is Int32
# Int32 is always truthy in a boolean context
```

**Comment by andraantariksa** [comment]
I guess Ameba also need to mark the code behow as unreachable

```
def foo
    if true
        return "reachable"
    end
    
    return "unreachable"
end
```

---

**Correct me if Im wrong**

From what I have know, Ameba is currently just analyzing the AST generated by Crystal. Such features will requires Ameba to run [Crystal type semantic analysis](https://github.com/crystal-lang/crystal/blob/0fa9550758e91f12ca3aa7fdf0ce01bc8123ddf2/src/compiler/crystal/semantic.cr#L69).

**Comment by veelenga** [comment]
> From what I have know, Ameba is currently just analyzing the AST generated by Crystal. Such features will requires Ameba to run Crystal type semantic analysis.

Yes, exactly.
