### ISSUE TITLE
[Feature Request] Relax Lint/ComparisonToBoolean to allow unions with Bool

### ISSUE THREAD

**Issue by HertzDevil** [crystal-ameba/ameba#171]
Comparisons to booleans are not pointless if the other operand is a union containing `Bool`:

```crystal
def f(x : Int32 | Bool)
  print 1 if x == true
  print 2 if x == false
  print 3 if x
  print 4 if !x
  puts
end

f(0)     # 3
f(true)  # 13
f(false) # 24
```

(Comparisons to unions not containing `Bool` are still pointless, as they *should* always evaluate to `false`.)

**Comment by veelenga** [comment]
In Crystal comparison to booleans can be used to narrow down the type of the variable, thus doing the static analysis, we are not able to properly handle this. Refs https://github.com/crystal-ameba/ameba/issues/12

```crystal
def f(x: Bool | Nil)
  if x == false
    # x is not Int32 and not Nil here.
  end
end
```
