### ISSUE TITLE
[Feature Request] .reject(Nil)

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-ameba/ameba#175]
I recently used the code
```cr
...
  .reject(&.nil?)
  .map(&.not_nil!)
```
but I learned (ty ary) there is a much better way.
```cr
...
  .reject(Nil)
```

**Comment by veelenga** [comment]
Thanks. But could you please elaborate on why it is a much better way for you? As for me, both variants are concise, readable, performant and I think we should not enforce that or another one.

**Comment by Daniel-Worrall** [comment]
Yeah, sorry.

I don't suppose it's any more performant, but I feel like it's more readable and concise than the other. Its intent is far clearer from a glance

This can also be extended to `.select(&.is_a?(Klass)).map(&.as(Klass))`.

**Comment by straight-shoota** [comment]
`.reject(Nil)` only iterates once.

**Comment by Daniel-Worrall** [comment]
Ah, yes, for Enumerable, but, not Iterable
