### ISSUE TITLE
[Feature Request] Detect duplicate requires

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#176]
This is probably a rare case, but I just found in lucky we had some duplicate requires in the same file. 

```crystal
require "./thing"
require "./stuff"
require "./thing"  # <-- would be neat if Ameba caught this
require "./other_stuff"
```

**Comment by veelenga** [comment]
Nice one. Wonder why the compiler doesn’t detect this

**Comment by jwoertink** [comment]
That's a good point. I think it just returns false if it's already been required. So maybe the compiler doesn't know the difference between "I can't require this" and "I've already required this"? ... though, I guess if it couldn't require it, it would just raise a compile-time error 🤔
