### ISSUE TITLE
Analysis of invidious repo takes a very long time

### ISSUE THREAD

**Issue by CaptainTyphoo** [crystal-ameba/ameba#177]
I am trying to analyze the [invidious repo](https://github.com/iv-org/invidious), but the analysis has been running for about 7 days now and the ameba process has accumulated about 17500 minutes of CPU time according to top. So far the output of ameba is just
```
$ ./ameba
Inspecting 36 files.
```

Are there settings to speed up the analysis? I already set `CRYSTAL_WORKERS=4` but ameba is not even using two full cores.

Is it supposed to take that long?

**Comment by veelenga** [comment]
@CaptainTyphoo hey, thanks for reporting.

I made a quick test and noticed it works well without a single rule `Lint/UselessAssign`. Try disabling it:

```
$ ameba --except Lint/UselessAssign
```

Seems like this rule is kinda inefficient and should be optimized.

**Comment by CaptainTyphoo** [comment]
Thank you! 
The analysis takes less than a second if I disable `Lint/UselessAssign`.

**Comment by veelenga** [comment]
Reduced:

```crystal
response = JSON.build do |json|
   json.object do
     json.object do
       json.object do
         json.object do
           json.object do
             json.object do
               json.object do
                 json.object do
                   json.object do
                     json.object do
                       json.object do
                         anything
                       end
                     end
                   end
                 end
               end
             end
           end
         end
       end
     end
   end
 end
 response = JSON.parse(response)
 response = prepare(response)
 response       

```
