### ISSUE TITLE
[Feature Request] Performance/JoinAfterMap

### ISSUE THREAD

**Issue by Sija** [crystal-ameba/ameba#183]
I see an opportunity to squash pretty common idiom of using `Enumerable#map(& : -> String)` + `#join(String)` together, amounting to double iteration, while one could use single transformation via `#join(String, & : -> String)` instead.

**Comment by veelenga** [comment]
I think there is a similar for `flat_map`

**Comment by Sija** [comment]
@veelenga `flat_map` I think is a bit kind of different animal as you can't use `join` with block to achieve the same effect as with `flat_map` + `join`
