### ISSUE TITLE
Possible Issue with Lint/UselessAssign

### ISSUE THREAD

**Issue by stephendolan** [crystal-ameba/ameba#194]
Hey there! Thank you to the contributors for this library, which has become a staple of my Crystal development.

To that end, I'm currently trying to help out the Stripe shard at https://github.com/confact/stripe.cr by getting them onto GitHub actions with Ameba checks. However, when I started cleaning up the repo, I noticed this kind of warning popping up all over the place:

```
src/stripe/methods/core/billing_portal/sessions/create_session.cr:8:5
[W] Lint/UselessAssign: Useless assignment to variable `customer`
> customer = customer.id if customer.is_a?(Customer)
  ^
```

That's coming from this line:
https://github.com/confact/stripe.cr/blob/master/src/stripe/methods/core/billing_portal/sessions/create_session.cr#L8

To the best of my knowledge, this variable _is_ being used down in the macro on this line:
https://github.com/confact/stripe.cr/blob/master/src/stripe/methods/core/billing_portal/sessions/create_session.cr#L13

I'll throw the full class in-line to make it easier to parse quickly:

```crystal
class Stripe::BillingPortal::Session
  def self.create(
    customer : String | Stripe::Customer,
    return_url : String? = nil,
    expand : Array(String)? = nil
  ) : Stripe::BillingPortal::Session
    customer = customer.id if customer.is_a?(Customer) # <---- Warning is thrown here

    io = IO::Memory.new
    builder = ParamsBuilder.new(io)

    {% for x in %w(customer return_url expand) %} # <---- But variable is used here
      builder.add({{x}}, {{x.id}}) unless {{x.id}}.nil?
    {% end %}

    response = Stripe.client.post("/v1/billing_portal/sessions", form: io.to_s)

    if response.status_code == 200
      Stripe::BillingPortal::Session.from_json(response.body)
    else
      raise Error.from_json(response.body, "error")
    end
  end
end
```

I can't speak to whether or not this is the "right" way to write this, but the codebase's tests pass and I'm using the class above successfully in production without issues. It's a pattern that's quite prevalent in the codebase (43 instances at the moment), so I'd rather not perform a bulk refactor if possible.

Is there perhaps another implementation of the line of code throwing the warning that I should be using? Happy to provide more details if necessary!

**Comment by veelenga** [comment]
Hey there. Thanks for the submission. 

```crystal
{% for x in %w(customer return_url expand) %} # <---- But variable is used here
  builder.add({{x}}, {{x.id}}) unless {{x.id}}.nil?
{% end %}
```

This is not true. The line you referring to only contains the array of strings (i.e. "customer"). Variable is used one line below, when `{{x.id}}` is called. The pattern is a bit tricky, and i would rather avoid the macro there for readability:

```crystal
builder.add("customer", customer) if customer
builder.add("return_url", return_url) if return_url
builder.add("expand", expand) if expand
```

However, that is your preference and it doesn't have to be reported by Ameba as (at least) UselessAssign. Minimal reproduction scenario: 

```crystal
foo = 1

{% for x in %w(foo) %}
  puts {{ x.id }}
{% end %}
```

**Comment by stephendolan** [comment]
Whoops, sorry @veelenga I see where the actual usage is! I'm going to edit my original submission so that it's more clear for folks that may come across this in the future.

I agree that this macro use might be a bit over the top. I'm just doing some "cosmetic" contributions at the moment, but plan to dive deeper into this code later when the maintainer ( @confact ) is comfortable.
