### ISSUE TITLE
Question on Performance/MapInsteadOfBlock

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#208]
I just ran ameba 0.14 against Avram, and got a lot of the `Performance/MapInsteadOfBlock` suggestions telling me "Use `join {...}` instead of `map {...}.join`". I wanted to see how much of a performance boost we were going to get from this, so I made a quick little sample:

```crystal
require "benchmark"

DATA = [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

def use_map_join
  DATA.map(&.to_s).join(", ")
end

def use_join
  DATA.join(", ") { |d| d.to_s }
end

Benchmark.ips do |x|
  x.report("map join") {
    use_map_join
  }
  x.report("join") {
    use_join
  }
end
```

But when I ran this, it tells me that the map/join variant is faster 🤔 

```
❯ ./speed
map join   2.81M (355.56ns) (± 4.78%)  353B/op        fastest
    join   1.83M (546.32ns) (± 3.48%)  337B/op   1.54× slower
```

I'm running this on
```
❯ crystal -v
Crystal 0.36.1 (2021-02-02)

LLVM: 11.0.1
Default target: x86_64-apple-macosx
```

Is there a specific case where the join with block is faster? (i.e. arrays over X amount of elements)

**Comment by jwoertink** [comment]
Ok, decided to try this against a larger array, also tested on Arch linux.

```crystal
require "benchmark"
DATA = {% begin %}
  [
    {% for i in 0..1000 %}
      {{i}},
    {% end %}
  ]
  {% end %}
def use_map_join
  DATA.map(&.to_s).join(", ")
end
def use_join
  DATA.join(", ") { |d| d.to_s }
end
Benchmark.ips do |x|
  x.report("map join") {
    use_map_join
  }
  x.report("join") {
    use_join
  }
end
```

On mac
```
map join  28.44k ( 35.16µs) (± 5.39%)  42.4kB/op        fastest
    join  18.37k ( 54.43µs) (± 4.99%)  51.0kB/op   1.55× slower
```

On Arch
```
map join  46.11k ( 21.69µs) (± 3.05%)  42.4kB/op        fastest
    join  35.70k ( 28.01µs) (± 2.37%)  51.0kB/op   1.29× slower
```

**Comment by Sija** [comment]
That's weird since the extra iteration + allocation (using `map`) should give the opposite results...

**Comment by kostya** [comment]
i think this should be fastest: `String.build { |io| DATA.join(io, ", ") }`

**Comment by straight-shoota** [comment]
The map call transforms the values to a string. That's cheating the benchmark. `Indexable#join` is highly optimized for string values.

If the map returns any other type, the results are different:
```
map join   2.27k (439.95µs) (± 7.84%)  296kB/op   1.13× slower
    join   2.57k (388.51µs) (± 2.52%)  257kB/op        fastest
```

```cr
require "benchmark"
DATA = (0..10000).to_a

Benchmark.ips do |x|
  x.report("map join") do
    DATA.map{ |i| i ** 2 }.join(", ")
  end
  x.report("join") do
    DATA.join(", ") { |i| i ** 2 }
  end
end
```

As kostya mentioned, if you have the string conversion in `map`, it'd even be more performant to use `join` with an `io` and call `to_s(io)`.

**Comment by jwoertink** [comment]
Yeah, that makes sense, though, it seems that Ameba doesn't take in to consideration on what the `map` is doing when it makes the suggestions. So in this case, we would have to go line by line and really measure whether or not Ameba was giving us a good suggestion. We could just ignore this ruleset, but it's been really nice just having the rule of "if Ameba says do it, then we do it".

**Comment by straight-shoota** [comment]
Yes, and the example used to describe the rule is already misleading (i.e. incorrect). `(1..3).join('.', &.to_s)` is *not* more efficient than `(1..3).map(&.to_s).join('.')`.

But `String.build { |io| (1..3).join(io, '.', &.to_s(io) }` is at least faster. It still allocates more memory than map join, though.

**Comment by veelenga** [comment]
That makes sense. Thank you, guys.

I will try adjusting the rule to report correctly.

**Comment by Sija** [comment]
@straight-shoota Wouldn't be possible to optimize `join(separator, & : _ -> String)` to essentially act as a `map` + (optimized) `join`?

**Comment by straight-shoota** [comment]
I suppose that might be a good idea.

**Comment by veelenga** [comment]
Closing this for now, since the rule was disabled in the latest release.
