### ISSUE TITLE
Input on Style/VerboseBlock

### ISSUE THREAD

**Issue by stephendolan** [crystal-ameba/ameba#214]
Hey, there! Forgive me if the Issues tab isn't the place for this, and I'll happily recreate this elsewhere if that's more helpful.

I was recently adding Ameba to a project, and noticed the following suggestion:

```
[C] Style/VerboseBlock: Use short block notation instead: `find(&.creator.==(user))`
> elsif user && (revision = snippet.revisions.find { |rev| rev.creator == user })
                                              ^--------------------------------^
```

This could totally be a personal thing where the answer is "If you don't like it, configure it off in your `.ameba.yml` file", but I thought I'd at least raise the question since I'm trying **very** hard to stick to a zero-customization version of Ameba. I went down the config-file-per-project route with RuboCop in my Ruby projects, and as a result I now pretty much exclusively use StandardRB to avoid maintaining those config files.

I *love* this correction for the simpler substitutions. If I were writing `snippet.revisions.map { |rev| rev.to_s }`, I'd certainly want Ameba to tell me that I should use `snippet.revisions.map(&.to_s)`.

However, for a `find` call like this, `find(&.creator.==(user))` seems to be more difficult to visually parse in the same way as `find { |rev| rev.creator == user }`, and a little bit less "pretty".

Again, I know this is somewhat personal and subjective, ~~and I'm not sure how to really "fix" this other than to not recommend `VerboxBlock` fixes for operations that require a comparator like `find`,~~ but thought I'd at least put it out into the universe in an attempt to continue not needing to manage a `.ameba.yml` config file.

**Comment by stephendolan** [comment]
Apologies for my poor research! It looks like the `ExcludeOperators` setting already exists, and does indeed remove this suggestion.

https://github.com/crystal-ameba/ameba/blob/master/src/ameba/rule/style/verbose_block.cr#L25

I suppose then, that this issue is more of a request/discussion about making that exclude operators by default rather than leaving them in scope for the suggestion by default.

**Comment by veelenga** [comment]
While the style rules are often a subject of discussion, my personal preferences match your suggestion. This was partially dicussed [here](https://github.com/crystal-ameba/ameba/pull/201#pullrequestreview-576064865).

@Sija any blockers on your side excluding the operators by default?

**Comment by Sija** [comment]
@veelenga Nope, I'm good with changing this default.

**Comment by stephendolan** [comment]
Excellent, thank you for the input, everyone!

I'd be thrilled to contribute a PR to close this issue, in that case. I'll do a bit more digging into the code, and submit that soon ™️ .
