### ISSUE TITLE
Question on Style/IsAFilter when using Nop in macros

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#219]
This might be more for a question on the Crystal side than Ameba itself, but this was where I noticed it...

We have this line in Lucky:

```crystal
{% raise "All arguments must have an explicit type for memoized methods" if method_def.args.any? &.is_a?(Nop) %}
```

and Ameba tells us to use the short version:

```
src/lucky/memoizable.cr:24:97
[C] Style/IsAFilter: Use `any?(Nop)` instead of `any? {...}`
> {% raise "All arguments must have an explicit type for memoized methods" if method_def.args.any? &.is_a?(Nop) %}
                                                                                              ^------------------^
```

After updating the code to `method_def.args.any?(Nop)`, I get this error:

```
❯ ~/Development/crystal/crystal-1.0.0-1/bin/crystal spec
Showing last frame. Use --error-trace for full trace.

In src/lucky/memoizable.cr:24:102

 24 | {% raise "All arguments must have an explicit type for memoized methods" if method_def.args.any?(Nop) %}
                                                                                                       ^--
Error: undefined constant Nop
```

I thought maybe it was some weird scope deal Crystal is doing, but even this doesn't work:

```
In src/lucky/memoizable.cr:24:102

 24 | {% raise "All arguments must have an explicit type for memoized methods" if method_def.args.any?(Crystal::Macros::Nop) %}
                                                                                                       ^-------------------
Error: undefined constant Crystal::Macros::Nop
```

So I guess the question is, should Ameba be aware of this weird edge case? Should I just disable ameba for this case? Or is this some weird Crystal bug?

/ cc. @straight-shoota

**Comment by straight-shoota** [comment]
The reason seems to be that ameba applies the same rules to the macro languages as to regular Crystal code. But `ArrayLiteral#any?` doesn't have an overload accepting a type. It must be called with a block. So ameba is just wrong here.

The compiler error is misleading of course, not sure what exactly is the reason. But I'd expect https://github.com/crystal-lang/crystal/pull/10498 to provide a more meaningful error message.

**Comment by jwoertink** [comment]
Ah, ok. Thanks for the info @straight-shoota!
