### ISSUE TITLE
Performance/AnyInsteadOfEmpty in spec context

### ISSUE THREAD

**Issue by veelenga** [crystal-ameba/ameba#220]
```
flash_store.any?.should be_true
```

is suggested to be:

```
!(flash_store.empty?).should
```

which is incorrect. 

refs https://github.com/luckyframework/lucky/pull/1447

**Comment by Sija** [comment]
I don't now how this could be solved sensibly. This problem persists throughout the whole ruleset - i.e. it's as easy as user defining a custom class with the same method name, that's being used in some rule(s), but under different assumptions.

**Comment by veelenga** [comment]
This problem persists throughout the performance ruleset only. We already had some discussion and tried to minimize the number of performance rules exactly because of the cases you describe. I think in the future we would move these rules to a separate shard i.e. `ameba/performance` so the users will enable them on demand.

To solve the original issue my suggestion is to exclude the specs from the list of files the performance rules run on. WDYT?

**Comment by Sija** [comment]
@veelenga Sounds legit 💪
