### ISSUE TITLE
Guidance on linking to a screencast

### ISSUE THREAD

**Issue by stephendolan** [crystal-ameba/ameba#225]
Hey, Ameba team!

This is easily one of my favorite Crystal shards, and I use it in every Crystal project I create. To help others see the light, I put together a LuckyCast on Ameba here:
https://luckycasts.com/videos/ameba

I wanted to know if you'd find value in a PR adding a link to this to the README (or somewhere else). My feelings won't be hurt at all of the answer is "no", since I completely understand the difficulty in keeping videos up-to-date and high quality as libraries change. One pretty example of a screencast link is in my [Decorator shard README](https://github.com/stephendolan/decorator#-screencast), though a plain link might also be helpful for new folks exploring the library.

Either way, thank you again for creating and maintaining such a valuable community tool.

**Comment by veelenga** [comment]
This looks awesome. I would be happy to see the link to the LuckyCast in the Readme. Would you like to submit a PR?

Thanks for making videos on LuckyCasts, great job 👍

**Comment by stephendolan** [comment]
I'll happily submit a PR! I'll do it in the same style as the Decorator shard README, and we can tweak it from there as you'd like 😄
