### ISSUE TITLE
Failed postinstall ameba

### ISSUE THREAD

**Issue by KanielOutis** [crystal-ameba/ameba#228]
```Error target ameba failed to compile:
In src/ameba/cli/cmd.cr:173:13

 173 | puts \
             ^
Error: unknown token: '\r'

**Comment by veelenga** [comment]
What's your OS and crystal version?

**Comment by KanielOutis** [comment]
> 
> 
> What's your OS and crystal version?

wsl ubuntu 20.04, crystal is 1.0.0

**Comment by KanielOutis** [comment]
it's ok, i had other issues with postinstall, i've tried `sudo shards install`  instead of  `shards install` and it work
