### ISSUE TITLE
Ameba failing shards install

### ISSUE THREAD

**Issue by backward-crazy-mage-puppy-36** [crystal-ameba/ameba#232]
MacOS catalina 10.15.7

When running shards install in a lucky framework test app shards install fails at

Postinstall make bin && make run_file
Failed make bin && make run_file:
shards build
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _*Crystal::Iconv#convert<Pointer(Pointer(UInt8)), Pointer(UInt64), Pointer(Pointer(UInt8)), Pointer(UInt64)>:UInt64 in C-rystal5858I-conv.o
  "_iconv_close", referenced from:
      _*Crystal::Iconv#close:Nil in C-rystal5858I-conv.o
  "_iconv_open", referenced from:
      _*Crystal::Iconv#initialize<String, String, (Symbol | Nil)>:Nil in C-rystal5858I-conv.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/bcmp36/code/crystal/lucky/testing/lib/ameba/bin/ameba  -rdynamic -L/usr/local/lib -L/opt/local/lib -lyaml -lpcre -lgc -lpthread /usr/local/Cellar/crystal/1.0.0/src/ext/libcrystal.a -L/opt/local/lib -levent -liconv -ldl`

make: *** [bin/ameba] Error 1

**Comment by veelenga** [comment]
Can you confirm you have libiconv installed locally?

**Comment by backward-crazy-mage-puppy-36** [comment]
> Can you confirm you have libiconv installed locally?

I didn't have it installed. installed it. still seeing the same error. 

Postinstall make bin && make run_file
  Failed make bin && make run_file:
  shards build
  Dependencies are satisfied
  Building: ameba
  Error target ameba failed to compile:
  Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
  _*Crystal::Iconv#convert<Pointer(Pointer(UInt8)), Pointer(UInt64), Pointer(Pointer(UInt8)), Pointer(UInt64)>:UInt64 in C-rystal5858I-conv.o
  "_iconv_close", referenced from:
  _*Crystal::Iconv#close:Nil in C-rystal5858I-conv.o
  "_iconv_open", referenced from:
  _*Crystal::Iconv#initialize<String, String, (Symbol | Nil)>:Nil in C-rystal5858I-conv.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Error: execution of command failed with code: 1: `cc "${@}" -o /Users/bcmp36/code/crystal/lucky/testing/lib/ameba/bin/ameba  -rdynamic -L/usr/local/lib -L/opt/local/lib -lyaml -lpcre -lgc -lpthread /usr/local/Cellar/crystal/1.0.0/src/ext/libcrystal.a -L/opt/local/lib -levent -liconv -ldl`

**Comment by kostya** [comment]
i think this is same: https://github.com/crystal-lang/crystal/issues/10653

**Comment by backward-crazy-mage-puppy-36** [comment]
> crystal-lang/crystal#10653

Sure. Looks similar. Though the error does not mention ameba, I tried everything that was suggested on that thread, nothing worked.

**Comment by veelenga** [comment]
Ameba embeds the crystal compiler, which apparently has a dependency on libiconv. That's why you see an error when compiling the ameba binary.

**Comment by Sija** [comment]
Closing this as it's not even ameba's issue _per se_. Also, the linked ticket was resolved with solutions.
