### ISSUE TITLE
New rule: comparison that always fails

### ISSUE THREAD

**Issue by docelic** [crystal-ameba/ameba#237]
As explained in https://github.com/crystal-lang/crystal/issues/10277, Crystal has a default/falback implementation of `==`, which allows any types to be compared, but it just evaluates to false.

Because of this, even comparisons which are useless or, worse, stem from a type error, are allowed and silently fail.

It would be great to add a new check that would be able to identify comparisons which always fail, such as:

```
'a' == "a"
Enum::Member == Int
Enum::Flag & Enum::Flag == Int
13 == GC
...
```

**Comment by Sija** [comment]
`Lint/LiteralInCondition` rule partially covers that btw.
