### ISSUE TITLE
Ameba-0.14.3 hangs with crystal-1.4

### ISSUE THREAD

**Issue by evgkrsk** [crystal-ameba/ameba#264]
After release of crystal-1.4 docker image, ameba-0.14.3 hangs infinitely.

**Steps to reproducte:**
- install crystal-1.4
- clone my repo: https://github.com/evgkrsk/reqs-up
- change dir to cloned path
- docker build -t test .

**Actual results:**
```
Inspecting 5 files
```
and constant CPU burning for in loooooong times...

**Expected results:**

ameba inspecting files and exits.

**Note**: rollback to crystal-1.3 base images fixes ameba behavior.

**Comment by straight-shoota** [comment]
This has been fixed in #259 but it's not released yet.
@veelenga @Sija Time for a new release!

As a workaround, you can use ameba master with Crystal 1.4 (add `branch: master` to the dependency in `shard.yml`).

**Comment by veelenga** [comment]
Yup, i am going to release 1.0

**Comment by veelenga** [comment]
https://github.com/crystal-ameba/ameba/releases/tag/v1.0.0
