### ISSUE TITLE
Function specific variables being declared as unused

### ISSUE THREAD

**Issue by h4ppyr0gu3** [crystal-ameba/ameba#266]
when using the following code: 
```File.write(output_filename, bytes, mode="wb")```
recieves error:
```
[W] Lint/UselessAssign: Useless assignment to variable 'mode'   
File.write(output_filename, bytes, mode="wb")
```

**Comment by veelenga** [comment]
This code actually creates an unused variable and passes it to the function. See how to use a named argument instead: https://crystal-lang.org/reference/1.4/syntax_and_semantics/default_and_named_arguments.html
