### ISSUE TITLE
`AnyInsteadOfEmpty` rule uses wrong node position

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#267]
In Lucky, we have a query method `.any?`. This actually runs SQL, so `Performance/AnyInsteadOfEmpty` rule here doesn't apply. 

This code passed on 0.14.4, but fails on 1.0.0
```crystal
TransactionQuery.new
  .receiver(user)
  .any? # ameba:disable Performance/AnyInsteadOfEmpty
```

```
src/serializers/post_serializer.cr:80:24 [Correctable]
[C] Performance/AnyInsteadOfEmpty: Use `!{...}.empty?` instead of `{...}.any?`
> TransactionQuery.new
  ^
```

Maybe solved by https://github.com/crystal-ameba/ameba/pull/265 ?

**Comment by Sija** [comment]
That's a regression, and shouldn't depend on #265 in any way.
