### ISSUE TITLE
Missing `--explain` descriptions

### ISSUE THREAD

**Issue by mloughran** [crystal-ameba/ameba#270]
When installing ameba via brew on macOS, the output of `--explain` includes the following:

```
...

## DETAILED DESCRIPTION

Error: Error opening file with mode 'r': '/private/tmp/ameba-20220516-71379-vydjhb/ameba-1.0.0/src/ameba/rule/performance/chained_call_with_no_bang.cr': No such file or directory
```

Presumably some [additional files need to be installed](https://docs.brew.sh/Formula-Cookbook#just-moving-some-files) by the [brew formula](https://github.com/veelenga/homebrew-tap/blob/master/ameba.rb#L13).

```
% brew list ameba
/opt/homebrew/Cellar/ameba/1.0.0/bin/ameba
```

**Comment by Sija** [comment]
hmm, now when I look at it I'm surprised it works at all, given that the source file from which the doc explanation comes, is being parsed at runtime (ouch) ;)

**Comment by Sija** [comment]
Repro steps:

- `git clone git@github.com:crystal-ameba/ameba.git __ameba__`
- `cd __ameba__`
- `shards build`
- `cp bin/ameba ~/`
- `cd ..`
- `rm -rf __ameba__`
- `~/ameba --explain <path>`

This already breaks the _explain_ feature. From now on, every invocation will end with this error (not being able to find the original source). Also, it's os-independent.
