### ISSUE TITLE
add support for param annotations

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#272]
introduced in crystal 1.5 crystal-lang/crystal#12039

```crystal
  @[AC::Route::GET("/param_annotation/:thing")]
  @[AC::Route::GET("/param_annotation/:thing/flexible", config: {thing: {strict: false}})]
  def test_param_annotation(
    @[AC::Param::Converter(class: IsHotDog, config: {strict: true})]
    thing : Bool
  ) : Bool
    thing
  end
```

leads to the following error

<img width="578" alt="image" src="https://user-images.githubusercontent.com/368013/185840821-7526c6fe-f522-42e7-a04f-309995372448.png">

**Comment by veelenga** [comment]
Could you please confirm that ameba's binary is compiled on crystal 1.5? If not, you can remove `bin/ameba` binary and recompile the binary.

**Comment by veelenga** [comment]
Also, i have just noticed ameba doesn't yet support crystal 1.5. I am going to prepare a new release soon:

https://github.com/crystal-ameba/ameba/blob/a8c00dbc15c3e9fb2e3003a6098a48fde08d21e6/shard.yml#L18

**Comment by stakach** [comment]
ahh yes, after removing the binary and running shards update we're all good
sorry to bother.
