### ISSUE TITLE
Get blocked forever when run with `bin/ameba`, but it works with prebuild ameba or `bin/ameba src`.

### ISSUE THREAD

**Issue by zw963** [crystal-ameba/ameba#274]
As you can see, it blocked forever

```
 ╰─ $ bin/ameba
Inspecting 4 files

.^C
```

You can check the github action [here](https://github.com/zw963/myip/actions/runs/3181058813/jobs/5185363589) too.

Thank you.

**Comment by zw963** [comment]
Sorry, in fact,  i found it not works on all case, i guess there maybe some issue with my code or misunderstood cause this block, could you please help on how to run it?

**Comment by zw963** [comment]
But it work well if run ameba from system $PATH directly instead of run project it self ameba.

```sh
 ╰─ $ ameba
Inspecting 5 files

F....

src/myip.cr:87:18
[W] Lint/UnusedArgument: Unused argument `i`. If it's necessary, use `_` as an argument name to indicate that it won't be used.
> size.times do |i|
                 ^

Finished in 2.2 milliseconds
5 inspected, 1 failure

 ╰─ $ 1  which -a ameba
/home/zw963/Crystal/git/ameba/bin/ameba
 ╰─ $ bin/ameba   # get blocked.
Inspecting 5 files

F^C
```



```

**Comment by veelenga** [comment]
Might be a duplicate of https://github.com/crystal-ameba/ameba/issues/264

Your action is running on ameba 0.14.4, which is very old and is affected by the issue above.

Could you please try upgrading to the latest version?

**Comment by zw963** [comment]
Yes, it works!  don't know why, not found the version issue.

thank you very much.

**Comment by zw963** [comment]
Sorry, i can know why my current CI still not work after update to 1.1.0?

https://github.com/zw963/myip/actions/runs/3192010102/jobs/5215464193

BTW:  both local and github action run successful as you can see.
