### ISSUE TITLE
[Feature Request] Search ~/.ameba.yml as a default config for current linux user.

### ISSUE THREAD

**Issue by zw963** [crystal-ameba/ameba#275]
As done like rubocop.

we probably have to merge project config with home config.

Thank you.

**Comment by veelenga** [comment]
Could you please elaborate on the following:

1. Which config should have priority?
2. Why `~/.ameba.yml` ?  XDG spec is more common for linux systems (i.e. ${XDG_CONFIG_HOME:-~/.config}/ameba/ folder)
3. How to let the user know that he has global defaults that override his config in the repo?
4. Could you please share what kind of config would you use as a default config? I think in many cases it might be useless, since having local defaults will not work on different machines or CI.

**Comment by zw963** [comment]
> * Which config should have priority?
> 

project config override home config

> * Why `~/.ameba.yml` ?  XDG spec is more common for linux systems (i.e. ${XDG_CONFIG_HOME:-~/.config}/ameba/ folder)
> 

~/.config/ameba/config.yml is fine.


> * How to let the user know that he has global defaults that override his config in the repo?
> 

I consider this is unnecessary,  if user add it, he knew it.

> * Could you please share what kind of config would you use as a default config? I think in many cases it might be useless, since having local defaults will not work on different machines or CI.

Most of usage is just disable many unwanted config globally, e.g. i have a ~/.rubocop.yml, which disable many rules, because, from my point of view, the default set of rubocop, is too aggressively for most of user.

In fact, when i use rubocop with ruby, not serve as CI purpose, it just a code style, which promote me all the time when i am coding use emacs, if some rule is useful, i will fix it, if some rule is not so comfortable with, i will disable all in my all project to avoid tips again and again.

**Comment by zw963** [comment]
Test on master, it works, thanks!

**Comment by zw963** [comment]
BTW, when user want to generate project config for CI purpose, like `bin/ameba --gen-config`, i consider it should ignore those global config in ~/.ameba.yml, otherwize, `bin/ameba` probably failed on CI, but passed on develop machine, this inconsist behavior probably make user confusing, what do you think?

**Comment by Sija** [comment]
Yup, that's a bug alright :) This should be for sure fixed before the release. I'm going off grid for a week though, so I'll be able to do it on the next weekend, the earliest.

**Comment by zw963** [comment]
Hi, i guess i can try to fix gen-config issue.

BTW: after i check the PR, i found there is no merge config logic, which exists in Rubocop, probably [here](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/config_loader.rb#L85-L90)

following is a example:

1. I disable rule `Lint/NotNil` in project_home/.ameba.yml, like this:

```yaml
Lint/NotNil:
  Description: Identifies usage of `not_nil!` calls
  Enabled: false
```

 2. i set `Style/ParenthesesAroundCondition` in ~/.ameba.yml, like this:

```yaml
Style/ParenthesesAroundCondition:
  Description: Disallows redundant parentheses around control expressions
  ExcludeTernary: false
  AllowSafeAssignment: true
  Enabled: true
  Severity: Convention
```

the rubocop config merge rule is use new ParenthesesAroundCondition style as a user global settings, but, will override only if same rule was set in DEFAULT_PATH config, that is, when i run `bin/ameba`, it should respect above both two rule. 

But, current solution is, global config was ignored because DEFAULT_PATH exists.

**Comment by zw963** [comment]
> I'd suggest to revert it then. I'll do a proper fix once I get back.

Maybe we can create a new issue for merge the DEFAULT_PATH into the first find DEFAULT_PATHS ?

-------

I try to fix the --gen-config issue, please check the #363

**Comment by zw963** [comment]
Hi, for my previous explain about merge in the above comment,  i guess i misunderstood the rubocop.

rubocop never merge the DEFAULT_PATH into the first found DEFAULT_PATHS, in fact, it behavior same as
this PR,  i was misunderstood because, there is a `inherit_from` in PROJECT_HOME/.rubocop.yml, like this:

```yaml
inherit_from:
  - ~/.rubocop.yml  # will inherit the $HOME/.rubocop.yml as default

# Add lints, which will override the lints exists in ~/.rubocop.yml
```

So, i consider we have done this feature,  for support `inherit_from` directive as rubocop, that will be another new feature, so, i consider there is no issue left for this feature.

Thanks.

**Comment by veelenga** [comment]
@zw963 makes sense.

I have just released https://github.com/crystal-ameba/ameba/releases/tag/v1.4.3 which includes the fix.
