### ISSUE TITLE
The not_nil! warnings aren't always caught

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#316]
Related: #284 

I just upgraded a project to Ameba 1.3.1, and ran it which caught a few instances of `not_nil!`, but it didn't catch all of them. 

```
app on  main [⇡] is 📦 v0.1.0 via 🔮 v1.6.2 
❯ ./bin/ameba 
Inspecting 32 files

................................

Finished in 33.43 milliseconds
32 inspected, 0 failures

app on  main [⇡] is 📦 v0.1.0 via 🔮 v1.6.2 
❯ ack "not_nil" src/ | wc -l
10

app on  staging is 📦 v0.1.0 via 🔮 v1.6.2 
❯ ack "not_nil" src/ | wc -l
14

app on  main [⇡] is 📦 v0.1.0 via 🔮 v1.6.2 
❯ ./bin/ameba -v
1.3.1
```

Looks like I still have 10 more uses of it in my code. I'm not using any ameba configs, or ignores.

**Comment by Sija** [comment]
Could you please post offending lines for further inspection?
Without any code samples it's impossible to say what's goin' on ;)

**Comment by jwoertink** [comment]
Sure!

```crystal
context.request.headers["X-Timestamp"].not_nil!.to_s
context.request.headers["X-User-ID"].not_nil!.to_s
context.request.headers["X-Identifier"].not_nil!.to_s
context.request.headers["X-Chunk-Count"].not_nil!.to_s
context.request.headers["X-Chunk-ID"].not_nil!.to_s
```

Also, I noticed that it caught all of the ones in `my_app/src/app` but not in `my_app/src/app/nested/dir` if that helps.

**Comment by Sija** [comment]
Thanks, will look into it!

**Comment by Sija** [comment]
Weird, works for me 🤔  Perhaps it's sth with your setup after all?

**Comment by jwoertink** [comment]
Strange. I'll try to re-create something using my setup here in a bit.

**Comment by Sija** [comment]
Being inside a macro might be a reason, would that be possible?

**Comment by jwoertink** [comment]
ah! Yeah, they're inside a `macro included` in a module :sweat_smile:

**Comment by Sija** [comment]
Can't do much with those, I'm afraid - or... @veelenga wdyt? :)

**Comment by jwoertink** [comment]
No worries then. I thought maybe it was a bug, so I wanted to make sure it was reported, but I'm ok with closing it out.

**Comment by Sija** [comment]
Sure, many thanks for reporting! 🦅 👀 ❤️

**Comment by veelenga** [comment]
> Can't do much with those, I'm afraid - or... @veelenga wdyt? :)

I don’t think it worst an effort to be more accurate in macro. Quite hard not to introduce false positives.

Thanks for reporting and digging in.
