### ISSUE TITLE
Lint/LiteralsComparison not always accurate

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#322]
```crystal
  ENVIRONMENT   = ENV["SG_ENV"]? || "development"
  IS_PROUCATION = ENVIRONMENT == "production"
```

results in an error: `[W] Lint/LiteralsComparison: Comparison always evaluates to false`

**Comment by Sija** [comment]
Fixed in https://github.com/crystal-ameba/ameba/commit/2cb8c1381fea0e5cb49fe4506d1780e382ad0b46. Will be available as a part of v1.4.0 release.
