### ISSUE TITLE
Images on Docker Hub are not being updated

### ISSUE THREAD

**Issue by Sija** [crystal-ameba/ameba#331]
SSIA

**Comment by Sija** [comment]
@veelenga Perhaps we should switch to GHCR?

**Comment by veelenga** [comment]
Docker Hub moved automated builds to pro version, so i stopped supporting it.

GHCR should be ideal :+1:

**Comment by Sija** [comment]
I don't think it makes sense to support both, so I'd vote to cleanup/lockdown the one on the DockerHub.

**Comment by Sija** [comment]
Technically speaking _we could_ push images to the both repos, I'm not sure whether it makes sense though. @veelenga wdyt?

**Comment by Sija** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/988/210271875-bab22aa5-8682-4b4c-95fc-7233b3b38887.png">

After looking at https://www.docker.com/pricing/ I'd ditch it after all.

**Comment by veelenga** [comment]
It is already abandoned 2 years ago, and don't see a reason to support two. 

I will keep the repo for legacy (some people still use it):

<img width="617" alt="image" src="https://user-images.githubusercontent.com/3624712/210316440-7dd22229-5ef2-49b6-8a63-ba5b87a631f4.png">
