### ISSUE TITLE
Autocorrect errors

### ISSUE THREAD

**Issue by veelenga** [crystal-ameba/ameba#34]
The ability to autocorrect sources using a list of found errors. For example, me as a user seeing this error:

```crystal
def has_user? # PredicateName: Favour method name 'user?' over 'has_user?'
end
```

would love to be able to automatically convert it to:

```crystal
def user?
end
```

Should be doable with `Crystal::Transformer`. Here is a simple example:

https://github.com/crystal-lang/crystal/blob/master/samples/compiler/transformer_example.cr

**Comment by hugoabonizio** [comment]
Awesome! But how to handle the cases where problems comes from third-party shards?

**Comment by veelenga** [comment]
We don't inspect third-party shards. `lib/` directory [is excluded](https://github.com/veelenga/ameba/blob/master/src/ameba/config.cr#L116) from the list of sources.

**Comment by hugoabonizio** [comment]
Actually I was thinking in this case: 
```crystal
if OtherLib.has_something?
  # ...
end
```
But I didn't realised Ameba only checks for methods definitions, not calls. Sorry!

**Comment by veelenga** [comment]
Ah, okay that is an interesting point. For this particular rule (PredicateName) that wouldn't be a case, because it is looking for the method definition, not the method call. So it will not report an error and there will be nothing to autocorrect. But there might be other rules which could do other inspections for third-party calls. Will keep this in mind, thank you.

**Comment by anicholson** [comment]
Oh yes please! I don't want to use a linter that doesn't fix the things it knows how to :)

**Comment by kostya** [comment]
in my project i have ~500 errors: `LargeNumbers: Large numbers should be written with underscores`, replace it by hands is pain.

**Comment by veelenga** [comment]
@kostya @anicholson any help is appreciated :)

**Comment by veelenga** [comment]
Closed by 

https://github.com/crystal-ameba/ameba/pull/248
