### ISSUE TITLE
[Feature request]: Json output

### ISSUE THREAD

**Issue by meatball133** [crystal-ameba/ameba#382]
It would be nice if the tool could output in JSON to make it easier to integrate with other platforms.

**Comment by veelenga** [comment]
It exists: 
https://github.com/crystal-ameba/ameba/blob/e1f5c818049a3341c598ef35b58287aa88b26f9b/src/ameba/formatter/json_formatter.cr#L4-L65

*Added for documentation purposes, just in case anyone else will land to this issue*
