### ISSUE TITLE
BUG: trying to downcast (Slice(UInt8) | Nil) (Crystal::MixedUnionType) <- Slice(UInt8) (Crystal::GenericClassInstanceType) (Exception)

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#397]
Just got this error against Crystal nightly when running CI for Lucky using Ameba 1.5.0

https://github.com/luckyframework/lucky/actions/runs/5722039908/job/15504511981?pr=1818#step:4:37

I'll file this on Crystal too, just in case.

**Comment by straight-shoota** [comment]
This was resolved with https://github.com/crystal-lang/crystal/issues/13720

**Comment by jwoertink** [comment]
Can confirm! I've gone back to a few projects and ran and got green 👍  Thanks!
