### ISSUE TITLE
Configure skipping directories

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#410]
It would be nice to be able to tell the CLI to skip certain directories. For example, in Lucky apps, if you use `lucky exec`, a crystal file is generated in `tmp/console/123.cr`. This file is a dumping ground for code and always hits ameba errors. I'd like to run `./bin/ameba --skip-dir=./tmp` or something along those lines so it will still check all my other directories outside of `./src/`, but just ignore `./tmp`.

Or if this is already possible, maybe the `-h` menu can add an example?

I'm currently using v1.5.0

**Comment by Sija** [comment]
Why not add `tmp` dir to the `Excluded` in `.ameba.yml`?

**Comment by jwoertink** [comment]
:joy:  thanks. I was looking up and down this and missed it.
