### ISSUE TITLE
warn on redundant use of `.try`

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#411]
not sure if possible, but would be cool if it could warn if `.try` is being used on something that is not nilable

```crystal
me = 123456
str = me.try &.to_s
puts str
```

**Comment by Sija** [comment]
not possible due to the lack of semantic analysis.

refs https://github.com/crystal-ameba/ameba/issues/170#issuecomment-771658055

**Comment by straight-shoota** [comment]
Having a linter that supports semantic analysis would be a nice feature in the future. Even if they're out of scope currently for ameba, their reasonable features that would be useful to the community. So regardless of whether it would end up as a feature enhancement of ameba or an entirely different project, I think it would be nice to collect such use cases somewhere.
Not sure if the best place for that would be in ameba's issue tracker or maybe the Crystal forum?
