### ISSUE TITLE
ComparisonToBoolean with Bool unions

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-ameba/ameba#432]
Given the following code:

```crystal
val = false || 10

if val == true
  pp "TRUE"
else
  pp val.to_s
end
```
This currently results in:
```cr
[W] Lint/ComparisonToBoolean: Comparison to a boolean is pointless
> if val == true
     ^---------^
```
However I think in this case it's a false positive since `val : Bool | Int32`, in which case you need the explicit comparison in order to not enter the `TRUE` block if `val` happens to be any number.

**Comment by Sija** [comment]
There's nothing that can be done here, short of introducing semantic analysis.

**Comment by Sija** [comment]
Duplicate of #171
