### ISSUE TITLE
exception names are too limited

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#433]
Currently the default ameba options seem too limited. `%w[e ex exception]`
I feel like this should include version common names like `error` but also it should probably add something like `|| begins_with?("#{allowed}_")` so nested exceptions can be handled like `ex_parse` `ex_io` etc

Also `e` is not very descriptive and breaks other rules like descriptive block naming.

**Comment by Sija** [comment]
> I feel like this should include version common names like `error`

It's not that common, therefore I didn't include it. You can add it to your project's `.ameba.yml` file.

> it should probably add something like `|| begins_with?("#{allowed}_")` so nested exceptions can be handled like `ex_parse` `ex_io` etc

I disagree, exception variables should IMO have unified names.

> Also `e` is not very descriptive and breaks other rules like descriptive block naming.

It shouldn't, since it's explicitly whitelisted:

https://github.com/crystal-ameba/ameba/blob/47088b10ca97aff96c9580ff50b17cd4e945a175/src/ameba/rule/naming/block_parameter_name.cr#L31

**Comment by stakach** [comment]
Seem pretty commonly used - can see you use it too @Sija 
https://github.com/search?q=%28language%3ACrystal+%29+AND+%22rescue+error%22&type=code

![image](https://github.com/crystal-ameba/ameba/assets/368013/690b1ce0-5fa9-4658-a1f3-e64adeece4af)

**Comment by stakach** [comment]
more common than `rescue exception`

![image](https://github.com/crystal-ameba/ameba/assets/368013/cb1140eb-ea00-44f3-b858-ca0a95544e78)

**Comment by stakach** [comment]
also missing `exc` which is also quite commonly used

![image](https://github.com/crystal-ameba/ameba/assets/368013/8c21e2b3-e7c2-4e7f-a698-ff19ae10b2d2)

**Comment by Sija** [comment]
Yeah, in the same time `rescue ex` has **6.9k** occurrences (~10x more than `rescue exc`) - i.e. all other uses are pretty marginal.

**Comment by stakach** [comment]
thanks mate!

**Comment by straight-shoota** [comment]
Perhaps use cases such as `ex_` prefix could be enabled with regex matching support?
