### ISSUE TITLE
spec helpers getting flagged

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/ameba#454]
this seems a little overbearing.
having it correctable breaks things too.

![image](https://github.com/crystal-ameba/ameba/assets/368013/7a577c1f-9517-43c0-b2c0-5ab44bc91d59)

prefixing the file with `spec_` solves the issue but that seems redundant given we're in a spec folder.
also seems to flag any file in there, even if it doesn't `require "spec"` or have any specs in it

maybe we could update this rule to only flag files if they contain actual specs?
i.e. if it's in the spec folder and has `describe` or `it` blocks in the file

**Comment by Sija** [comment]
Hi, first of all the _overbearing_ adjective could be used for any perceived noise, and I don't see any specific relation to this particular rule.

Secondly, the convention is to name the helper as `spec_helper.cr`, which by default is ignored by `SpecFilename` rule.

Thirdly, you can either:

- add the files/folders glob(s) as a part of rule's `Excluded` setting
- add the helper files/folders as a part the rule configuration, see `IgnoredDirs` and `IgnoredFilenames` properties:
    https://github.com/crystal-ameba/ameba/blob/63be60ce96543e8dd91fcbe100d4a299f8f16870/src/ameba/rule/lint/spec_filename.cr#L15-L16
