### ISSUE TITLE
Custom macro generates "Useless assignment to variable"

### ISSUE THREAD

**Issue by petr-fischer** [crystal-ameba/ameba#456]
Example correct code:

```crystal
class AAA 
  macro reactive_property(declaration)
  end 

  property placeholder_key : String?
  reactive_property placeholder_key2 : String?
  reactive_property in_edit = false                                                                                                                             
end
```

Then:
```bash
docker pull ghcr.io/crystal-ameba/ameba
docker run --rm -v "$(pwd):/src" ghcr.io/crystal-ameba/ameba
```

Wrong output:

```bash
test.cr:6:21
[W] Lint/UselessAssign: Useless assignment to variable `placeholder_key2`
> reactive_property placeholder_key2 : String?
                    ^------------------------^

test.cr:7:21
[W] Lint/UselessAssign: Useless assignment to variable `in_edit`
> reactive_property in_edit = false
                    ^-----^
```

Related: #77

**Comment by veelenga** [comment]
I think this was explicitly noted here https://github.com/crystal-ameba/ameba/pull/430#issuecomment-1871646886 that such cases can't (or very hard) to be properly handled. There is a property `exclude_type_declarations` which excludes the type declarations, however will not help here with a second example (`in_edit` property).

@Sija would you like to hop-in? Should we add another property to handle that?

**Comment by petr-fischer** [comment]
OK, so I'm sticking with the ignore rules in the config. Thanks for the recheck and explanation.
