### ISSUE TITLE
`Naming/BlockParameterName` with ignored names

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#457]
Related: https://github.com/crystal-ameba/ameba/issues/453

I have a block parameter that starts with `_` indicating that this value is ignored, but since it still has a single letter, Ameba picks it up as a name that shouldn't be used

![image](https://github.com/crystal-ameba/ameba/assets/2391/ed7888d6-5f1b-4e00-b46f-ecbd47ce3e24)

Maybe for this option, if the block parameter starts with `_` then Ameba could ignore it regardless of what it's called?

**Comment by veelenga** [comment]
Yes, it can be defenitely ignored
