### ISSUE TITLE
Add rule enforcing explicit return

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#467]
While implicit return is nice, sometimes it can cause unintended effects / footguns. Would it be possible to add a (disabled by default) rule that's the exact opposite of [Style/RedundantReturn](https://crystaldoc.info/github/crystal-ameba/ameba/v1.6.1/Ameba/Rule/Style/RedundantReturn.html), encouraging the use of explicit returns?

**Comment by straight-shoota** [comment]
Could you show a case where implicit return would be a footgun?

**Comment by straight-shoota** [comment]
I suppose this requires semantic analysis for being any good. Without a semantic pass you dont know which code paths are `NoReturn`. So it would require `return` where no value is returned at all.

So at this point `ameba` cannot implement this.

**Comment by Sija** [comment]
Without semantic analysis that's going to be pretty useless, as mentioned already by @straight-shoota.
