### ISSUE TITLE
False positive `Lint/UselessAssign`

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-ameba/ameba#468]
```cr
hash = {"foo" => "bar"}

def call(v)
end

unless v = hash["foo"]?
  call v = "default"
end

v
```
Results in:
```cr
[W] Lint/UselessAssign: Useless assignment to variable `v`
> unless v = hash["foo"]?
```
The assignment is for sure not useless as it handles assigning `v` if that key is present in the hash, otherwise is assigned within the `unless` block.

Creating a new issue as unlike https://github.com/crystal-ameba/ameba/issues/447, this doesn't require any type declarations or macros.

**Comment by Sija** [comment]
Reduced:

```cr
unless (v = rand) > 0.5
  puts v = 1
end

v
```

**Comment by Sija** [comment]
I'd say the bug is most likely located somewhere in the `AST::ScopeVisitor` class, yet I couldn't exactly pinpoint it.

@veelenga any pointers?
