### ISSUE TITLE
Q: I can't build ameba with make

### ISSUE THREAD

**Issue by kojix2** [crystal-ameba/ameba#477]
This might be a very basic issue, and I might be missing something obvious, but I need some advice.

I tried the basic git clone and make process, but it failed:

```
git clone https://github.com/crystal-ameba/ameba
cd ameba
make
```

```
make: Nothing to be done for `all'.
```

What? I haven't built ameba in this directory before, so why am I seeing this message?

Next, I tried to install ameba using Homebrew, but it also failed:

```
brew tap crystal-ameba/ameba
brew install ameba
```

```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - bin/ameba
```

The error message says it can't find `bin/ameba`, so I suspect it's related to the same issue.

Since this is such a basic step, I thought it might be something wrong with my environment. So I forked the ameba repository and ran `make` using GitHub Actions CI, but it failed with the same error.

https://github.com/kojix2/ameba/actions/runs/11265560789/job/31327589181
https://github.com/crystal-ameba/ameba/compare/master...kojix2:ameba:u1

![image](https://github.com/user-attachments/assets/c5e34379-a225-4fa4-b9de-9d64d3427042)

I might be missing something obvious, but this is the first step most people would try. There are probably others who faced the same issue and gave up on ameba. This might be a silly question, but I'm posting here, believing that there are at least ten people who have encountered the same problem.

**Comment by Sija** [comment]
@straight-shoota Any ideas?

**Comment by straight-shoota** [comment]
This is seems to be an issue with `make` on macOS. Note the Ubuntu job works fine: https://github.com/kojix2/ameba/actions/runs/11265560789/job/31327588813.
I thought macOS uses GNU make so there shouldn't be a significant difference in operation. 🤔

**Comment by straight-shoota** [comment]
Ah, so it looks like the `::=` assignment operator is a GNU extension and not available in other Make implementations.
