### ISSUE TITLE
Add rule prohibiting type declarations for local vars with a keyword name

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#503]
Would fix issues like [this](https://github.com/crystal-lang/crystal/issues/9124).

Most of the time these aren't intentional and don't work.

```cr
icr:1> rescue : String = "hello"
 => "hello"
icr:2* puts rescue
icr:3*
```

```cr
icr:4> next : Int32 = 0
 => 0
icr:5> puts next
syntax error in :1
Error: void value expression
```

(forall is only kinda a keyword and thus works, still think it should be disallowed though)
```cr
icr:6> forall : String = "time"
 => "time"
icr:7> puts forall
time
 => nil
```

**Comment by Sija** [comment]
All of these seem to me more like a Crystal bugs than anything else.
Aside of this, I don't consider adding type declaration to local vars as sth generally wanted or useful tbh.

**Comment by nobodywasishere** [comment]
This is an explicitly supported use-case by the parser, but only useful when passed to `getter`/`property` macros (i.e., `Foo.rescue`).

> I don't consider adding type declaration to local vars as sth generally wanted or useful tbh.

This isn't about adding type declarations to local vars, it's giving a warning when there is a type declaration on a local var and the var name is a keyword.

**Comment by Sija** [comment]
I see. This IMO should be handled by Crystal parser, not a linter. I don't think we should warn about a valid parser constructs.

**Comment by nobodywasishere** [comment]
That's fair. I personally think keywords shouldn't be allowed as method / var / param names at all (maybe a different rule?), but that may be too much of a breaking change. Just thought this would be an easy win for a potential footgun.
