### ISSUE TITLE
Add rule prohibiting method / vars with a keyword name

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#505]
Similar to #503, but this expands it to all method / macro / variable names instead of just local vars.

**Comment by Sija** [comment]
Similarly to the mentioned PR, I see no point in having such a rule. That's up to the Crystal parser.

**Comment by nobodywasishere** [comment]
The Crystal parser cannot do anything here - this is an explicitly allowed use-case for the parser and of the language itself (not a bug), and changing this would be a breaking change. However, I think that this can lead to issues and confusion, and should be discourage, hence this rule proposal.

**Comment by nobodywasishere** [comment]
I have a prototype of an implementation for this [here](https://github.com/nobodywasishere/ameba/commit/5f121bc6065cbdf775d30335eebd80d4379c85d3). Everything works except for macro names / parameters and not sure exactly why.

**Comment by Sija** [comment]
I'm still not convinced for any practical usefulness of such rules.
Please provide compelling use-cases for limiting perfectly valid language constructs.

**Comment by nobodywasishere** [comment]
> limiting perfectly valid language constructs

Isn't this what ameba / a linter in general is for?

It is a personal preference of mine, and something that can lead to unintentional bugs and confusion. On top of that, for parameters and local vars, there's no way to reference them. I (personally) want to know when I'm writing code that breaks this rule, and ameba is an amazing tool for being able to do that.

**Comment by Sija** [comment]
> Isn't this what ameba / a linter in general is for?

Sure, yet there need to be a good justification for doing so, not _just_ a personal preference.

> something that can lead to unintentional bugs and confusion

Some examples would help to clarify what exactly do you mean by that.

> On top of that, for parameters and local vars, there's no way to reference them.

Could you please post examples of such behaviour?

AFAIK method parameters with illegal names for instance are being properly reported as syntax error, see:

```cr
def foo(break)
end

# Fails with `Error: cannot use 'break' as a parameter name`
```

Other cases should be reported as a parser bugs in Crystal repo.
