### ISSUE TITLE
Add `Lint/UnusedLiteral`

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#508]
Similar to #235 (and potentially solving #467), I think it would be useful if there was a linting rule `Lint/UnusedLiteral` that reported when there was a literal value in a void context:

```crystal
def something : Bool
  if cond
    true
  # ^^^^ error: Literal value is not used
  end
  false
end
```

There would be _some_ overlap with `Lint/UselessComparison` if a literal is in an unused comparison, but maybe there can be a config option to not warn if inside an unused comparison(?).

**Comment by Sija** [comment]
Sounds like a great addition, 👍 from me.
