### ISSUE TITLE
Add `Style/MultilineCurlyBlock`

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#523]
This should give a warning when using a multi-line curly block:

```crystal
test_block {
         # ^ error: Use `do`...`end` for multi-line blocks
  puts "hello"
  puts "world"
}
```

Looking at the AST, it doesn't look like there's an easy way to tell if a block is created using curly brackets or `do`...`end`, unless I'm missing something. Do you know @straight-shoota?

**Comment by straight-shoota** [comment]
Yeah the type of block delimiter is not stored in the node. The only relevant difference is right vs. left binding, but that's already encoded in the AST. For semantics they are indifferent.

**Comment by nobodywasishere** [comment]
Could do a slightly hacky thing of taking the start position for the block and checking the source code to get the char, but would rather do an upstream parser/AST node update to be cleaner.

**Comment by straight-shoota** [comment]
Ameba has access to the source code and interacts with it directly for automatic corrections. So I suppose it shouldn't be too hard to look up the delimiter in the source.

As I said, the compiler doesn't have any use for this information in the AST, so adding it upstream in the parser is questionable.
