### ISSUE TITLE
Add GitHub Actions Workflow Command output format

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#525]
Related to https://github.com/crystal-ameba/github-action/issues/19

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions

Would just require outputting in these formats:
```
::notice file={name},line={line},endLine={endLine},title={title}::{message}
::warning file={name},line={line},endLine={endLine},title={title}::{message}
::error file={name},line={line},endLine={endLine},title={title}::{message}
```

**Comment by Sija** [comment]
This, I believe, should be implemented in the ameba's GitHub Action, not here. Relevant ticket is already created there, thus I'm gonna close this one.

**Comment by nobodywasishere** [comment]
This _could_ be implemented there, but I want to use ameba in CI without using that GitHub action (and without creating a new bespoke one).

**Comment by Sija** [comment]
@nobodywasishere That's a good point. @veelenga WDYT ?

**Comment by veelenga** [comment]
We can add a "GithubWorkflow" formatter, which will re-used in the action.
