### ISSUE TITLE
Affected code context

### ISSUE THREAD

**Issue by Sija** [crystal-ameba/ameba#93]
Just the affected line alone doesn't always provide enough information, thus oftentimes it's helpful to see several (ought to be configurable, usually 3/5 is a good default) lines of context before and after it.

**Comment by veelenga** [comment]
Yeah, i also was thinking about that but decided to make it simple at the beginning. We can be even more dynamic displaying multiple lines taking into account node.location, nide.end_location. But haven’t decided the best way yet
